name: boostsecurity.io
run-name: ${{fromJSON(github.event.inputs.scan_params).run_name}}
permissions: {}
on:
  workflow_dispatch:
    inputs:
      job_name:
        description: Name of the job to run
        required: false
      scan_params:
        description: The scan parameters
        required: true

jobs:
  boost-scanner:
    name: ${{fromJSON(github.event.inputs.scan_params).trigger_id}}
    runs-on: ubuntu-latest
    steps:
      - name: ${{fromJSON(github.event.inputs.scan_params).trigger_id}}
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_token: ${{secrets.BOOST_API_TOKEN}}
          trigger_id: ${{fromJSON(github.event.inputs.scan_params).trigger_id}}

  malware-detection:
    name: Malware Detection
    runs-on: ubuntu-latest
    steps:
      - name: Dump scan trigger payload
        run: |
          PAYLOAD=$(curl -s -H "Authorization: ApiKey ${{secrets.BOOST_API_TOKEN}}" "https://api.boostsecurity.io/ci-provisioning/scan/trigger?trigger_id=${{fromJSON(github.event.inputs.scan_params).trigger_id}}
          echo "BOOST_GIT_BRANCH=$(echo $PAYLOAD | jq -r .git_branch)" >> $GITHUB_ENV
          echo "BOOST_GIT_MAIN_BRANCH=$(echo $PAYLOAD | jq -r .git_main_branch)" >> $GITHUB_ENV
          echo "BOOST_GIT_HEAD=$(echo $PAYLOAD | jq -r .git_head_ref)" >> $GITHUB_ENV
          echo "BOOST_GIT_PROJECT=$(echo $PAYLOAD | jq -r .git_project)" >> $GITHUB_ENV
          echo "BOOST_GIT_REMOTE_URL=$(echo $PAYLOAD | jq -r .git_remote_url)" >> $GITHUB_ENV
          echo "GH_TOKEN=$(echo $PAYLOAD | jq -r .git_token)" >> $GITHUB_ENV

      - name: Clone
        uses: actions/checkout@v3
        with:
          repository: ${{ env.BOOST_GIT_PROJECT }}
          ref: ${{ env.BOOST_GIT_BRANCH }}
          token: ${{ env.GH_TOKEN }}
      
      # - name: malcontent
      #   uses: boostsecurityio/boostsec-scanner-github@v4
      #   with:
      #     registry_module: boostsecurityio/malcontent
      #     api_token: ${{secrets.BOOST_API_TOKEN}}
      #   env:
      #     BOOST_SCANNER_REGISTRY_REPO: https://github.com/boostsecurityio/dev-registry.git#boost-mw-poc
