name: boostsecurity.io
run-name: ${{fromJSON(github.event.inputs.scan_params).run_name}}
permissions: {}
on:
  workflow_dispatch:
    inputs:
      job_name:
        description: Name of the job to run
        required: false
      scan_params:
        description: The scan parameters
        required: true

jobs:
  boost-scanner:
    name: ${{fromJSON(github.event.inputs.scan_params).trigger_id}}
    runs-on: ubuntu-latest
    steps:
      - name: ${{fromJSON(github.event.inputs.scan_params).trigger_id}}
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_token: ${{secrets.BOOST_API_TOKEN}}
          trigger_id: ${{fromJSON(github.event.inputs.scan_params).trigger_id}}

  malware-detection:
    name: Malware Detection
    runs-on: ubuntu-latest
    steps:
      - name: Dump scan trigger payload
        run: |
          curl -s -H "Authorization: ApiKey ${{secrets.BOOST_API_TOKEN}}" "https://api.boostsecurity.io/ci-provisioning/scan/trigger?trigger_id=${{fromJSON(github.event.inputs.scan_params).trigger_id}}" | jq .

      # - name: Clone
      #   uses: actions/checkout@v3
      
      # - name: malcontent
      #   uses: boostsecurityio/boostsec-scanner-github@v4
      #   with:
      #     registry_module: boostsecurityio/malcontent
      #     api_token: ${{secrets.BOOST_API_TOKEN}}
      #   env:
      #     BOOST_SCANNER_REGISTRY_REPO: https://github.com/boostsecurityio/dev-registry.git#boost-mw-poc
